name: "My actions"
description: "Test my actions"

inputs:
  message:
    description: "The message"
    required: true
    default: "Not message"

runs:
  using: "composite" # Son un tipo, nos permite agrupar pasos comunes

  steps:
  - name: HelloWorld
    run: echo "${{ inputs.message }}"
    shell: bash