name: With services & Variables Entorno
on: [push]
jobs:
  services-env:
    runs-on: ubuntu-latest

    # ENV Se puede a nivel job
    env:
      MY_ENV: my_var

    services: # Los servicios se basan en contenedores de docker, podemos obtenerlo de su pagina oficial
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
    
    steps:
    - name: ls
      # ENV Se puede a nivel step
      env:
        MY_ENV_2: my_var_in_step
      run: echo "Mi variable $MY_ENV y $MY_ENV_2"