name: Hola mundo
on: [push, pull_request]
jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola mundo
      run: echo "Hola Mundo"

    - name: touch file
      run: touch hello.txt

    - name: set info
      run: echo "Hola Mundo" >> hello.txt

    - name: cat file
      run: cat hello.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: ls
      run: ls -al