name: Test Workflow Dispatch

# on: workflow_dispatch # Si solo queremos que nos permita seleccionar nuestra rama
on:  
  workflow_dispatch: # La siguiente forma configuramos entradas
    inputs:
      comment:
        description: "Comments"    
        required: false
        default: 'No comment'


jobs:
  test-ls:
    runs-on: ubuntu-latest

    steps: 
    - name: ls
      run: ls -la
    
    - name: echo Comment
      run: echo "${{ inputs.comment }}"